### PR TITLE
fix: implemented workaround for PAGE_KERNEL_EXEC on newer linux kernel

### PR DESCRIPTION
**Pull request by robert-burger**
this implements a workaround to enable allocation of kernel executable memory from loadable modules.

### CODE REVIEW

**Comment by robert-burger** [comment]
any news about that? changes needed?

**Comment by pbruenn** [comment]
Hi Robert, I'm very sorry that I haven't replied to you yet. The change looks very promising, but I just haven't got around to testing it in our home yet. Somehow it got lost. I've planned to do it tomorrow, so if you don't get any feedback from me in the next few days, please ping me again - I definitely want to try it out and merge it if it works.

**Comment by pbruenn** [comment]
@robert-burger finally, I can give feedback. It is working! At least on Debians " 6.1.0-22-rt-amd64". Currently, I am cleaning up my branch to repair my internal CI. Some things I want to change in your patch:
- put all the new code into LINUX_VERSION_CODE
- change the commit message to something like: "bbapi: make it compatible for Linux >= v5.8 ... in v5.8 __vmalloc() with  PAGE_KERNEL_EXEC was made unavailable for kernel modules. With the help of kprobes we are able to bring it back for now" 


EDIT: you find a preview here: https://github.com/Beckhoff/BBAPI/tree/patrickbr/try-github

**Comment by robert-burger** [comment]
done

**Comment by pbruenn** [comment]
merged as https://github.com/Beckhoff/BBAPI/commit/b2c381370b1bbf5b08afe89dd715ff0a7cbba55c

**Pull request closed without merging**
